name: Jira Create issue
description: Create a new Jira issue
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  servicedesk:
    description: Service desk ID
    required: true
  issuetype:
    description: "Type of the issue to be created. Example: 'Get IT help'"
    required: true
  summary:
    description: Issue summary
    required: true
  description:
    description: Issue description
    required: false
  raiseOnBehalfOf:
    description: Raise issue on behalf of someone
    required: false
  fields:
    description: Additional fields in JSON format
    required: false
outputs:
  issue:
    description: Key of the newly created issue
runs:
  using: 'node16'
  main: './dist/index.js'
